# Generated by Django 2.2.28 on 2022-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220910_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=0, max_length=10, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
    ]
